var flashcards = 
    {
        "Lesson Eight Vocabulary":
        [{"answer": "bliss",
          "question": "Extreme joy, leading to contentment"},
         {"answer": "compassion",
          "question": "The feeling of sharing the suffering of another"},
         {"answer": "dismay",
          "question": "a.  To discourage; to upset\nb.  A sudden loss of courage or confidence, due to danger"},
         {"answer": "ecstatic",
          "question": "Overwhelmingly joyful; intensely delighted"},
         {"answer": "endear",
          "question": "To inspire friendly, affectionate feelings; to cause to be liked"},
         {"answer": "exasperate",
          "question": "To annoy greatly; to aggravate or irritate; to anger"},
         {"answer": "forlorn",
          "question": "Lonely; abandoned; sad"},
         {"answer": "somber",
          "question": "Dark; gloomy"},
         {"answer": "sullen",
          "question": "Bad tempered in a quiet, gloomy way; sulky"},
         {"answer": "wretched,",
          "question": "Miserable; dreadful"}
        ],
        "Lesson Seven Vocabulary":
        [{"answer": "abstain",
          "question": "a.  To not do something by choice\nb.  To not vote"},
         {"answer": "acknowledge",
          "question": "a.  To admit the truth, existence, or reality of something\nb.  To show you have received something"},
         {"answer": "advocate",
          "question": "a.  To recommend; to write or speak in favor of a cause\nb.  A person who argues for a cause"},
         {"answer": "coalition",
          "question": "An alliance of people, parties, or nations"},
         {"answer": "conform",
          "question": "To follow rules or customs"},
         {"answer": "invalid",
          "question": "Not effective or legal"},
         {"answer": "justify",
          "question": "To demonstrate that something is right or fair; to defend with reasons"},
         {"answer": "sanction",
          "question": "a.  To permit or approve of an action\nb.  To punish a nation or group that has broken accepted laws"},
         {"answer": "underlie",
          "question": "a.  To provide a basis of support\nb. To lie under"},
         {"answer": "uphold",
          "question": "To maintain or support in the face of possible opposition"}
        ],
        "Lesson Six Vocabulary":
        [{"answer": "contemplate",
          "question": "To consider carefully and thoughtfully"},
         {"answer": "	conviction",
          "question": "a.  A very strong belief or opinion\nb.  Being found guilty"},
         {"answer": "disseminate",
          "question": "To make widely known; to spread"},
         {"answer": "engross",
          "question": "To occupy the mind completely; absorb"},
         {"answer": "intuition",
          "question": "A feeling; a sense; understanding gained without thinking"},
         {"answer": "lucid",
          "question": "Easily understood; clear"},
         {"answer": "moral",
          "question": "a.  Conforming to a standard or right or good behavior\nb.  The lesson taught by a story, a fable, or an event"},
         {"answer": "profound",
          "question": "Deep; deeply thought or reasoned"},
         {"answer": "puritanical",
          "question": "Strict in matters of religious or moral conduct"},
         {"answer": "sanctify",
          "question": "To make holy or sacred"}
        ],
        "Lesson Five Vocabulary":
        [{"answer": "amelioration",
          "question": "The act of making better or improving"},
         {"answer": "assuage",
          "question": "To relieve or make less difficult"},
         {"answer": "compensate",
          "question": "a.  To pay\nb.  To make up for"},
         {"answer": "conserve",
          "question": "To protect from wasteful loss"},
         {"answer": "constructive",
          "question": "Serving a helpful and positive purpose"},
         {"answer": "enhance",
          "question": "To make better or more valuable"},
         {"answer": "enrichment",
          "question": "The act of making something richer or better; improvement"},
         {"answer": "neutralize",
          "question": "To cancel an effect or render it harmless"},
         {"answer": "preservation",
          "question": "The act of keeping something in good health or condition"},
         {"answer": "redeem",
          "question": "a.  To recover or buy back\nb.  To restore honor, worth, or value"}
        ],
        "Unit Two Stems":
        [{"question": "archy\nExamples: monarchy, oligarchy, hierarchy, anarchy, matriarchal, patriarch\nOrigin: Greek",
          "answer": "government"},
         {"question": "ard\nExamples: drunkard, coward, braggart, dullard, sluggard\nOrigin: Germanic",
          "answer": "always"},
         {"question": "cide\nExamples: herbicide, homicide, matricide, suicide, genocide\nOrigin: Latin",
          "answer": "kill"},
         {"question": "ician\nExamples: technician, musician, beautician, physician, statistician, clinician\nOrigin: Latin",
          "answer": "specialist"},
         {"question": "itis\nExamples: appendicitis, tonsillitis, arthritis, gastroenteritis\nOrigin: Greek",
          "answer": "inflammation"},
         {"question": "aqua\nExamples: aquarium, aquatic, aqueduct, aquifer, semiaquatic\nOrigin: Latin",
          "answer": "water"},
         {"question": "audi\nExamples: audiophile, audience, audition, auditory, audiometer, audit, audiology\nOrigin: Latin",
          "answer": "hear"},
         {"question": "bell\nExamples: belligerent, rebel, counter-rebellion\nOrigin: Latin",
          "answer": "war"},
         {"question": "cap\nExamples: capture, captive, captor, captivate, captivity, caption, capsule\nOrigin: Latin",
          "answer": "take"},
         {"question": "cise\nExamples: excise, incisors, incision, circumcise, incisive, precise, concise, decision\nOrigin: Latin",
          "answer": "cut"},
         {"question": "bio\nExamples: biography, biology, biochemistry\nOrigin: Greek",
          "answer": "life"},
         {"question": "auto\nExamples: autobiography, automobile, autography, automatic, automation, automaton, autocracy\nOrigin: Greek",
          "answer": "self"},
         {"question": "port\nExamples: transport, import, report, porter, deport, important, portage, portly\nOrigin: Latin",
          "answer": "carry"},
         {"question": "scrib\nExamples: scribble, inscribe, scribe, describe, conscription, transcribe, ascribe\nOrigin: Latin",
          "answer": "write"},
         {"question": "logy\nExamples: biology, anthropology, geology, entomology, mythology\nOrigin: Greek",
          "answer": "science"},
         {"question": "dict\nExamples: dictionary, predict, malediction, dictation, addict, contradict\nOrigin: Latin",
          "answer": "say"},
         {"question": "cred\nExamples: credit, incredible, credible, incredulous, discredited, credibility, credo\nOrigin: Latin",
          "answer": "believe"},
         {"question": "cent\nExamples: century, bicentennial, centimeter, centipede, centurion\nOrigin: Latin",
          "answer": "one hundred"},
         {"question": "neo\nExamples: neologism, neon, Neolithic, neoclassic, neonatal, neophyte\nOrigin: Greek",
          "answer": "new"},
         {"question": "ad\nExamples: adhesive, adapt, addendum, addition, adherent, addict, advent, advocate\nOrigin: Latin",
          "answer": "to"},
         {"question": "cede\nExamples: recede, precede, antecedent, proceed, seceded, concede, intercede, succeed\nOrigin: Latin",
          "answer": "go"},
         {"question": "miss\nExamples: dismiss, remiss, missile, admission, missionary, emission, promissory\nOrigin: Latin",
          "answer": "send"},
         {"question": "centri\nExamples: centrifugal, centrist, concentric, decentralize, eccentric\nOrigin: Greek",
          "answer": "center"},
         {"question": "biblio\nExamples: bibliography, bibliophile, bible, bibliomania, bibliophobia, bibliolatry\nOrigin: Greek",
          "answer": "book"},
         {"question": "anthropo\nExamples: anthropology, anthropoid, misanthrope\nOrigin: Greek",
          "answer": "man"}],
        "Vocabulary Lesson 4": 
        [
            {"answer": "allure",
             "question": "a.  A strong fascination or attraction; the power to attract\nb.  To attract with something desirable; entice"},
            {"answer": "avid",
             "question": "Eager; very enthusiastic"},
            {"answer": "devotion",
             "question": "Complete dedication to a cause or person"},
            {"answer": "effusive",
             "question": "Unrestrained or excessive in emotional expression; gushing"},
            {"answer": "exhilaration",
             "question": "Excited happiness"},
            {"answer": "fanatic",
             "question": "A person excessively and unreasonable devoted to a cause or belief"},
            {"answer": "indifferent",
             "question": "a.  Not interested in or concerned about something; not caring\nb.  Not good or bad; mediocre"},
            {"answer": "jubilant",
             "question": "Filled with joy"},
            {"answer": "reticent",
             "question": "a.  Unwilling; reluctant\nb.  Private about one’s affairs; tending to say little"},
            {"answer": "zealous",
             "question": "Highly motivated by dedication to a cause, an ideal, or a goal"}
        ],
        "Vocabulary Lesson 3":
        [
            {"answer": "brusque",
             "question": "Rough and short in manner or speech; abrupt; curt"},
            {"answer": "cordial",
             "question": "Warm and friendly"},
            {"answer": "dignity",
             "question": "a.  A calm manner indicating self-respect and worthiness\nb.  A sense of self-respect"},
            {"answer": "hospitable",
             "question": "Open and welcoming to guests"},
            {"answer": "irksome",
             "question": "Annoying; irritating"},
            {"answer": "nicety",
             "question": "a.  A small, often unimportant detail; a fine point\nb. An elegant detail or distinction; a refined feature or custom"},
            {"answer": "propriety",
             "question": "The quality of being proper; appropriateness"},
            {"answer": "refined",
             "question": "Very polite and cultured"},
            {"answer": "suave",
             "question": "Sophisticated; smoothly agreeable and polite"},
            {"answer": "tact",
             "question": "The ability to speak or act without offending others"}
        ],
        "Unit One Stems": [
            {"question": "ante\nOrigin: Latin\nExamples:antedate, antecedent, antebellum, anterior, ante meridiem\n",
             "answer": "before"},
            {"question": "anti\nO{rigin: Greek\nExamples:antibody, anticlimax, anticline, antitoxin, antithesis anti-aircraft\n",
             "answer": "against"},
            {"question": "bi\nOrig{in: Latin\nExamples:bilateral, bicycle, binary, bimonthly, biped, bipolar, binocular, bicuspid\n",
             "answer": "two"},
            {"question": "circum\nOrigin: Latin\nExamples:circumnavigate, circumspect, circumvent, circus\n",
             "answer": "around"},
            {"question": "com\nOrigin: Latin\nExamples:combination, comfort, commensurate, common, complete, combo\n",
             "answer": "together"},
            {"question": "con\nOrigin: Latin\nExamples:contract, confidence, confine, confederate, conjunction, contact\n",
             "answer": "together"},
            {"question": "de\nOrigin: Latin\nExamples:deposit, descent, despicable, denounce, deduct, demolish, decrepit, deplete\n",
             "answer": "down"},
            {"question": "dis\nOrigin: Latin\nExamples:distract, distort, dispute, dissonant, disperse, dismiss, dissuade, disprove\n",
             "answer": "away"},
            {"question": "equi\nOrigin: Latin\nExamples:equitable, equilateral, equivocate, equinox, equation, equilibrium\n",
             "answer": "equal"},
            {"question": "extra\nOrigin: Latin\nExamples:extraterrestrial, extraordinary, extravagant, extrovert, extramural\n",
             "answer": "beyond"},
            {"question": "inter\nOrigin: Latin\nExamples:international, interdepartmental, interstellar, interject, interlude\n",
             "answer": "between"},
            {"question": "intra\nOrigin: Latin\nExamples:intracellular, intravenous, intracranial, intrastate\n",
             "answer": "within"},
            {"question": "intro\nOrigin: Latin\nExamples:introduce, introspective, introvert, introject, intromission\n",
             "answer": "into"},
            {"question": "mal\nOrigin: Latin\nExamples:malevolent, malcontent, malicious, malign, malady, malapropism, malonym\n",
             "answer": "bad"},
            {"question": "mis\nOrigin: Germanic\nExamples:misfit, mistake, misfortune, misfire, misdeed, misguided\n",
             "answer": "bad"},
            {"question": "non\nOrigin: Latin\nExamples:nonstop, nonprofit, nonconformity, nonplussed, nonchalant\n",
             "answer": "not"},
            {"question": "post\nOrigin: Latin\nExamples:postgraduate, posthumous, postscript, posterity, posterior, postlude\n",
             "answer": "after"},
            {"question": "pre\nOrigin: Latin\nExamples:prelude, preposition, premonition, premature, predict, predecessor\n",
             "answer": "before"},
            {"question": "semi\nOrigin: Latin\nExamples:semitone, semiaquatic, semicircle, semiweekly, semiannual, semiformal\n",
             "answer": "half"},
            {"question": "sub\nOrigin: Latin\nExamples:subterranean, subtract, subordinate, submarine, subterfuge, substantial\n",
             "answer": "under"},
            {"question": "super\nOrigin: Latin\nExamples:supervise, superb, superior, superfluous, supercilious, supernatural\n",
             "answer": "over"},
            {"question": "sym\nOrigin: Greek\nExamples:sympathy, symbiosis, symbol, symmetry, symphony, symposium\n",
             "answer": "together"},
            {"question": "syn\nOrigin: Greek\nExamples:synthetic, synchronize, syndrome, synonym, synopsis, syntax\n",
             "answer": "together"},
            {"question": "tri\nOrigin: Greek\nExamples:tricycle, triangle, triceps, triad, trichotomy, triceratops, trivia, trialogue\n",
             "answer": "three"},
            {"question": "un\nOrigin: Old English\nExamples:unfit, unequal, undone, unequivocal, unearned, unconventional, untenable\n",
             "answer": "not"}
        ],
        "Vocabulary Lesson 1":
        [
{"question": "Shortened, usually in reference to a written or spoken word.",
"answer": "abridged"},
{"answer": "browse",
"question": "a.  To look over reading material, sampling different parts\nb.  To look at in a leisurely and casual manner"},
{"answer": "citation",
"question": "a.  A reference to or a quotation from an authority\nb.  An official award for honorable behavior\nc.  An official order stating that one must appear in court"},
{"answer": "compendium",
"question": "a.  A short but complete written summary\nb.  A collection that includes a variety of written works"},
{"answer": "entry",
"question": "a.  In a reference book, a subject or word and information about it \nb.  The means or place by which to come in"},
{"answer": "etymology",
"question": "The origin and history of a word"},
{"answer": "gazetteer",
"question": "A dictionary of geographical places, including names and information"},
{"answer": "homonym",
"question": "A word having the same pronunciation as another word but a different meaning form that word"},
{"answer": "lexicon",
"question": "a.  A dictionary\nb.  The vocabulary of a particular subject or group"},
{"answer": "phonetics",
"question": "The study of the sounds of a language"}
        ],
        "Vocabulary Lesson 2":
[
{"answer": "clarify",
"question": "To make clear or understandable"},
{"answer": "confide",
"question": "To trust someone with private or secret information"},
{"answer": "disclose",
"question": "To reveal or to open to view"},
{"answer": "enlighten",
"question": "To inform or give new insight"},
{"answer": "exhibit",
"question": "a.  To show or arrange for public display\nb.  A display"},
{"answer": "expound",
"question": "To explain in detail or talk at length about a particular topic"},
{"answer": "ingrained",
"question": "Deep-seated; firmly imprinted or fixed"},
{"answer": "misconception",
"question": "A mistaken idea"},
{"answer": "sage",
"question": "a.  Wise; showing great wisdom\nb.  A person respected for experience and wisdom"},
{"answer": "seminar",
"question": "A class or a conference held to discuss ideas on a topic."
}
]
    };
